# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... } : {
  imports = [
    ../hardware/amdcpu.nix
    ../hardware/amdgpu.nix
    ../hardware/ssd.nix
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  boot = {
    loader = {
      timeout = 2;
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "acpi_call" ];
    kernelModules = [ "acpi_call" ];
    kernelParams = ["acpi_backlight=native" ];
    kernelPackages = pkgs.linuxPackages_latest;
  };

  hardware.trackpoint = {
    enable = lib.mkDefault true;
    emulateWheel = lib.mkDefault config.hardware.trackpoint.enable;
  };

  services.xserver.monitorSection = ''
    DisplaySize 310 175
  '';

  services.fwupd = {
    enable = true;
    enableTestRemote = true;
  };
  #services.fprintd.enable = true;
  services.tlp.enable = lib.mkDefault true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3605938b-fc96-44f8-94c7-424426b76314";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6333-886D";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/6ef4dcff-6b05-4cca-90e9-d403958e0531"; }
  ];

  nix.maxJobs = lib.mkDefault 16;
}
