#! /bin/sh

bspc config border_width        1
bspc config window_gap          0
bspc config focused_border_color \#268bd2
bspc config active_border_color  \#93a1a1
bspc config normal_border_color  \#586e75
bspc config urgent_border_color  \#dc322f

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
#bspc config top_padding         16

bspc rule -a URxvtQuake sticky=on floating=on

#bspc monitor DisplayPort-0 -d A B C D
#bspc monitor DisplayPort-2 -d E F G H
#bspc monitor DisplayPort-1 -d I J K L

#pgrep redshift &> /dev/null || redshift &> /dev/null &
feh --bg-fill --no-xinerama ~/pictures/solarized_senketsu_1920.png
#start-pulseaudio-x11
#feh --bg-fill --no-xinerama ~/Pictures/SolarNyanPLPloading2.png
#trayer --edge bottom --align right --tint 0x002b36 --transparent false --heighttype pixel --height 16 --widthtype request &
#feh --bg-fill --no-xinerama ~/Pictures/SolarNyanPLPloading3.png
#owncloud &
#blueberry-tray &
#feh --bg-fill --no-xinerama ~/Pictures/SolarNyanPLPloading4.png
#xmodmap -e "keycode   9 = Super_L NoSymbol Super_L"
#feh --bg-fill --no-xinerama ~/Pictures/SolarNyanCatPLP.png
#numlockx on
