#! /usr/bin/env sh

cd "$(dirname "$0")"

CONFIG_HOST="$(hostname)"

if [ ! "$1" == "" ]; then
    CONFIG_HOST="$1"
fi

CONFIG_FILE="$(pwd)/machines/${CONFIG_HOST}/configuration.nix"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "No configuration found for ${CONFIG_HOST}"
    exit 1
fi

ln -vis "$CONFIG_FILE" /etc/nixos/configuration.nix
