chip "nvme-pci-0100"
	label temp1 "NVMe 1TB Composite"
	label temp2 "NVMe 1TB Sensor 1"
	label temp3 "NVMe 1TB Sensor 2"

chip "nvme-pci-0400"
	label temp1 "NVMe 2TB Composite"
	label temp2 "NVMe 2TB Sensor 1"
	label temp3 "NVMe 2TB Sensor 2"

bus "i2c-0" "SMBus PIIX4 adapter port 0 at 0b00"
chip "jc42-i2c-0-18"
	label temp1 "DIMM A1"
chip "jc42-i2c-0-19"
	label temp1 "DIMM A2"
chip "jc42-i2c-0-1a"
	label temp1 "DIMM B1"
chip "jc42-i2c-0-1b"
	label temp1 "DIMM B2"
