[[profile]]
name = "Home Desk Only"
	[[profile.output]]
	search = [ "v=Dell Inc.", "m=U2412M", "s=504H12CR656S" ]
	enable = true
	scale = 1
	mode = "best"
	transform = "90"
	position = "-1200,-190"
	[[profile.output]]
	search = [ "v=LG Electronics", "m=27GL850", "s=910NTTQ7B705" ]
	enable = true
	scale = 1
	mode = "best"
	adaptive_sync = true
	position = "0,0"
	[[profile.output]]
	search = [ "v=Dell Inc.", "m=U2412M", "s=9W5YH35M1KFL" ]
	enable = true
	scale = 1
	mode = "best"
	position = "2560,-190"
	transform = "270"
