chip "asusec-isa-*"
	label fan1 "Chipset Fan"
	label temp1 "Chipset"
	label temp2 "CPU Socket"
	label temp3 "Motherboard"
	label temp4 "Case"
	ignore temp5

chip "nvme-pci-0300"
	label temp1 "NVMe 256GB Composite"
	label temp2 "NVMe 256GB Sensor 1"
	label temp3 "NVMe 256GB Sensor 2"

chip "nct6798-isa-*"
	ignore in0
	ignore in1
	ignore in2
	ignore in3
	ignore in4
	ignore in5
	ignore in6
	ignore in7
	ignore in8
	ignore in9
	ignore in10
	ignore in11
	ignore in12
	ignore in13
	ignore in14
	ignore fan5
	ignore pwm5
	ignore fan7
	ignore pwm7
	ignore temp10
	ignore temp11
	ignore temp12
	ignore intrusion0
	ignore intrusion1
	ignore beep_enable
